env:
  global:
    - PACKAGE_VERSION="$(node -p -e 'require("./package.json").version')"
notifications:
  email: false
sudo: false
os:
- linux
language: node_js
node_js:
- 16
addons:
  apt:
    packages:
    - libsecret-1-dev

before_install:
- if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
  fi
script:
# - npm test --silent
- npm run vscode:prepublish

before_deploy:
- npm install -g vsce
- vsce package

deploy:
  - provider: releases
    api_key:
      secure: [GitHub Token]
    file_glob: true
    file: "*.vsix"
    skip_cleanup: true
    name: "Version ${PACKAGE_VERSION}"
    on:
      repo: [Reposity]
      tags: true